### ISSUE TITLE
SavableObjectEditor not enumerating object properties

### ISSUE THREAD

**Issue by tylercamp** [SoftFluent/SoftFluent.Windows#1]
I've modified the example project to have an Address object in the Customer object, with the template specified as SavableObjectEditor. Expanding the single object within the PropertyGrid opens the editor but no values are specified. Is this expected behavior?

**Comment by tylercamp** [comment]
I declare the property as such:

`[PropertyGridOptions(EditorDataTemplateResourceKey = "ObjectEditor")]
`public Address SimpleAddress { get { return GetProperty<Address>(); } set { SetProperty(value); } }

**Comment by smourier** [comment]
Yes, it's normal because the object is null. There is nothing built-in to create instances of objects automatically (with custom code, you could do it). But if you add this to the Model's constructor,

`            SimpleAddress = new Address();
`

Then you will see the adress properties when you edit it.

**Comment by tylercamp** [comment]
Wow, can't believe I forgot to initialize... Thank you!
