### ISSUE TITLE
Tab-Focusable Issue

### ISSUE THREAD

**Issue by ShannonZ** [SoftFluent/SoftFluent.Windows#10]
I think the column bound to DisplayName should not be focusable. This can be implemented by adding ` <Setter Property="Focusable" Value="False"/>` to the relevant style section.
At the same time, the Editor should be focusable. But **why there need press the tab key twice to change the focus from a editor to another**?

**Comment by smourier** [comment]
This is really a design decision, but as you found out, it's quite easy to change using XAML (or code). The grid tries to be consistent with the behaviorof  other property grids such as the standard Winforms' one: https://msdn.microsoft.com/en-us/library/aa302326.aspx.

You need to press TAB twice because in the general case there's one TAB to give focus to the editor's cell (from there you can navigate up/down/left/right still in the grid), and one TAB to give focus to the editor itself, the editor being dependent on the property (type). What the keyboard does in this editor is entirely dependent on the editor. For example, if the editor is a ComboBox (drop down), you will be able to select another item, while still using the keyboard.

**Comment by ShannonZ** [comment]
Thank you so much！
