### ISSUE TITLE
More complicated editor

### ISSUE THREAD

**Issue by ShannonZ** [SoftFluent/SoftFluent.Windows#15]
![capture-10](https://user-images.githubusercontent.com/7865691/30407187-6313b974-9929-11e7-88ea-4afbc69dac2f.gif)

I've searched in the demo but found no relevant examples. How to customize this kind of editors? The data showed in a listbox/DataGrid should be editable.

**Comment by smourier** [comment]
In a way, all editors are custom since they are all defined in XAML. The one that are closer to yours are the one that have a browse ("...") button on the right. They show a WPF window when pressed.

In the sample, there is for example "AddressListEditor" which is used for the Addresses property. It's a fully specific WPF window defined in AddressListEditorWindow.xaml.

To be able to use a WPF window as an editor, just have a look at how this is declared in App.xaml. You'll have to declare a DataTemplate which will define the value cell of the property grid:

        <DataTemplate x:Key="AddressListEditor">
            <DockPanel LastChildFill="true" ToolTip="{Binding Value, Mode=OneWay}">
                <Button IsEnabled="{Binding IsReadWrite}" Width="24" HorizontalContentAlignment="Center" Content="..." DockPanel.Dock="Right"
                        Command="{x:Static sfw:PropertyGrid.BrowseCommand}" CommandParameter="AddressListEditorWindow" />
                <TextBox IsReadOnly="True"
                         Background="{Binding IsDefaultValue, Converter={StaticResource BoolToDefaultValueBackgroundConverter}}" 
                         Text="{Binding TextValue, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" 
                         DockPanel.Dock="Left" />
            </DockPanel>
        </DataTemplate>

As you see, there's a textbox and a button, and this button has a BrowseCommand. This is defined by the PropertyGrid. The parameter of this command is the key of resource that points to the custom window:

        <samples:AddressListEditorWindow x:Shared="False" x:Key="AddressListEditorWindow" />

**Comment by ShannonZ** [comment]
I make custum editor using a textbox and a button. The editor displays in main window correctly. After click the button, I want to expand an expander which is also in the main window, not another one. Then how to write the Command bound to the button?

**Comment by smourier** [comment]
This is not an issue, the project is open source so you can find your way in it. I'm not doing consulting, no offense.

**Comment by ShannonZ** [comment]
I've learned a lot from the AddressListEditorWindow. And now I can calling an MetroWindow Flyout in my editor. Thanks for your help.
