### ISSUE TITLE
How to disable cell selection highlighting?

### ISSUE THREAD

**Issue by my151and** [SoftFluent/SoftFluent.Windows#16]
I used a textbox+slider as a customized editor. But when select the slider, the whole data grid cell was highlighted. This is ugly. Is it possible to disable  cell selection highlighting?
![1](https://user-images.githubusercontent.com/33822968/33004921-5bda9466-cdfe-11e7-82f7-ed6bd749e6e8.png)

**Comment by smourier** [comment]
Are you talking about the red box or the blue rectangle?

**Comment by my151and** [comment]
The blue background.
The red box was drawn using mspaint~

**Comment by smourier** [comment]
If you're using the sample datatemplate called PercentEditor, which is this:

        <DataTemplate x:Key="PercentEditor">
            <Slider ToolTip="{Binding TextValue}" Orientation="Horizontal" IsSnapToTickEnabled="True"
                    Value="{Binding Value, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged, Converter={StaticResource ChangeTypeConverter}, ConverterParameter={x:Type sys:Double}}"
                    Minimum="0"
                    Maximum="100"
                    Interval="1"
                    IsEnabled="{Binding IsReadWrite}"
                    Background="{Binding IsDefaultValue, Converter={StaticResource BoolToDefaultValueBackgroundConverter}}"></Slider>
        </DataTemplate>

Then you can just force Background to the color of your choice, like this:

        <DataTemplate ...>
            <Slider ...
                    Background="White">
            </Slider>
        </DataTemplate>

**Comment by my151and** [comment]
Thank you very much. And I think your solution is good for simple applications. But in my project, the skin/theme （including colors） was dynamically changed at runtime. Is it possible to bind the background color of an editor to this of the main window? If possible, how?

**Comment by smourier** [comment]
Just declare a WPF binding to something you want, instead of 'White'.

The DataContext in the property grid DataTemplate is an instance of the PropertyGridProperty class https://github.com/SoftFluent/SoftFluent.Windows/blob/master/SoftFluent.Windows/SoftFluent.Windows/PropertyGridProperty.cs corresponding to the selected object's property.

As you see, in the sample, Background was bound to the IsDefaultValue property of PropertyGridProperty , but you can declare a binding to anything you want. This is WPF.

**Comment by my151and** [comment]
A nice solution! Sorry to not reading your source code.
