### ISSUE TITLE
Editing object in sub-editor does not refresh display of object

### ISSUE THREAD

**Issue by tylercamp** [SoftFluent/SoftFluent.Windows#3]
I use the ObjectEditor to edit a sub-object, and that sub-object has a ToString definition that enables a quick view. After editing the sub-object, the ToString will have changed, but the view does not refresh for that new value. Since editing sub-objects does not fire PropertyChanged, I can't refresh the object manually.

**Comment by smourier** [comment]
By default the grid doesn't hook sub objects' events. That's by design, so you first need to hook the sub properties yourself, something like this with an property of type Address:

        public Address SubObject
        {
            get { return GetProperty<Address>(); }
            set
            {
                // because it's a sub object we want to update the property grid when inner properties change
                var so = SubObject;
                if (so != null)
                {
                    so.PropertyChanged -= OnSubObjectPropertyChanged;
                }

                if (SetProperty(value))
                {
                    so = SubObject;
                    if (so != null)
                    {
                        so.PropertyChanged += OnSubObjectPropertyChanged;
                    }
                }
            }
        }

        private void OnSubObjectPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            OnPropertyChanged(nameof(SubObject), false, true);
        }

Now this raises the PropertyChanged event for the 'SubObject' property, but the grid has protection to avoid refreshing the grid for no reason. So by default nothing happens because the SubObject instance does not change. So it required more work to force the grid to refresh. It was possible, but to ease things. I've updated the code so now you can declare the property forces a refresh by adding an attribute to it, something like this:

        [PropertyGridOptions(ForcePropertyChanged = true)]
        public Address SubObject
        {...}

I've also updated the whole sample to reflect this changes, I've added two linked SubObject property with one that has sub properties. Make sure you get the latest version.
