### ISSUE TITLE
Quirk presentation when using MahApp Controls in Custom Editors

### ISSUE THREAD

**Issue by ShannonZ** [SoftFluent/SoftFluent.Windows#9]
Demo solution: https://drive.google.com/open?id=0B9QI8E5qFmuEYzhfcXRJb3V0SEU
[Mah_SF.zip](https://github.com/SoftFluent/SoftFluent.Windows/files/1227091/Mah_SF.zip)  (the same with the google drive link)

`<DataTemplate x:Key="MyEditor">
                <Controls:NumericUpDown  Value="{Binding Value, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" 
                                         Minimum = "0" Maximum = "100"  Interval ="1" StringFormat="0"
                                         HideUpDownButtons = "false"/>
            </DataTemplate>` 

` [PropertyGridOptions(EditorDataTemplateResourceKey = "MyEditor")]
        public int age { set; get; } = 18;`

When running, the NumericUpDown shows nothing in the textbox.

**Comment by ShannonZ** [comment]
I have found the problem. I didn't implement the Converter.

**Comment by smourier** [comment]
It works fine with a standard WPF TextBox for example, so I guess the issue is related to this custom NumericUpDown control.

MahApp controls is beyond my reach, so I'll be of little help here, however this control NumericUpDown expects a double? value and if you change your definition for this

    [PropertyGridOptions(EditorDataTemplateResourceKey = "MyEditor")] public int age { set; get; } = 18;

you'll see it works fine. So I guess it's a conversion issue of some sort.
